# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

site_name: Google Dotprompt
repo_url: https://github.com/google/dotprompt
docs_dir: docs
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  logo: assets/google-logo-small.png
  favicon: assets/google-logo-small.png
  font:
    text: Fira Sans
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.footer
    - content.code.copy
    - content.code.annotate
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
plugins:
  - autorefs
  - d2
  - tags
  - mermaid2
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - python/dotpromptz/src
            - python/handlebarrz/src
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_root_heading: true
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            # Prevent docstring headings from polluting the TOC
            docstring_section_style: spacy
            heading_level: 3
            # Only show the summary/first line of module docstrings
            show_docstring_description: true
            show_docstring_examples: false
            show_docstring_other_parameters: true
            show_docstring_parameters: true
            show_docstring_raises: true
            show_docstring_returns: true
            show_docstring_warns: true
            show_docstring_yields: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
nav:
  - Home: index.md
  - Extending:
    - extending/index.md
    - Specification: extending/specification.md
    - Picoschema: extending/picoschema.md
  - API Reference:
    - api/index.md
    - Python:
      - dotpromptz: api/python/dotpromptz.md
      - handlebarrz: api/python/handlebarrz.md
    - TypeScript/JavaScript: api/typescript/index.md
    - Go: api/go/index.md
    - Rust: api/rust/index.md
    - Dart: api/dart/index.md
    - Java: api/java/index.md
  - Contributing:
    - contributing/index.md
    - Coding Guidelines: contributing/coding_guidelines.md
    - Git Workflow: contributing/git_workflow.md
    - Releases: contributing/releases.md
    - Packaging Rust: contributing/packagin_rust.md
    - Troubleshooting: contributing/troubleshooting.md
  - Design:
    - Promptly: design/promptly.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/firebase/genkit
    - icon: fontawesome/brands/discord
      link: https://discord.gg/qXt5zzQKpc
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/Firebase
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/Firebase
