# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Publish Python Packages to PyPI

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "The exact release tag(handlebarrz or dotpromptz) to publish"
        required: true
        type: string
      target:
        description: "Publish destination (TestPyPI or PyPI)"
        type: choice
        required: true
        options:
          - testpypi
          - pypi

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build distributions
    runs-on: ubuntu-latest
    env:
      PATH: ${{ github.workspace }}/.cargo/bin:${{ github.workspace }}/.local/\
            bin:/usr/local/bin:/usr/bin:/bin
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get isntall -y build-essential curl libffi-dev

      - name: Set up Rust (for handlebarrz)
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: '3.12'

      - name: Build handlebarrz (maturin)
        working-directory: python/handlebarrz
        run: |
          uv pip install maturin[patchelf] twine
          maturin build --release --strip -o dist
          maturin sdist -o dist
          twine check dist/*

      - name: Upload handlebarrz artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-handlebarrz
          path: python/handlebarrz/dist/

      - name: Build dotpromptz(python -m build)
        working-directory: python/dotpromptz
        run: |
          uv pip install build twine
          python -m build
          twine check dis/*

      - name: Upload dotpromptz artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-dotpromptz
          path: python/dotpromptz/dist/

  publish_handlebarrz:
    name: Publish handlebarrz to PyPI
    needs: build
    runs-on: ubuntu-latest
    env:
      PYPI_REPOSITORY_URL: ${{ inputs.target == 'testpypi' && 'https://test.pypi.org/legacy/' || 'https://upload.pypi.org/legacy/' }}
    steps:
      - name: Checkout code at tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-handlebarrz
          path: dist/

      - name: Publish handlebarz to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          packages-dir: dist/
          repository-url: ${{ env.PYPI_REPOSITORY_URL }}

  # Publish dotprmptz only after handlebarrz
  publish_dotpromptz:
    name: Publish dotpromptz to PyPI
    # Enforce order: This job waits until publish_handlebarz is successful
    needs: [build, publish_handlebarrz]
    runs-on: ubuntu-latest
    env:
      PYPI_REPOSITORY_URL: ${{ inputs.target == 'testpypi' && 'https://test.pypi.org/legacy/' || 'https://upload.pypi.org/legacy/' }}
    steps:
      - name: Checkout code at tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-dotpromptz
          path: dist/

      - name: Publish dotpromptz to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          packages-dir: dist/
          repository-url: ${{ env.PYPI_REPOSITORY_URL }}
