name: proto_example
description: Example demonstrating Dart proto and gRPC code generation with Bazel.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  protobuf: ^3.1.0
  grpc: ^4.0.0

dev_dependencies:
  test: ^1.25.0
